name: Build and Deploy Gatsby to Netlify
#  cron job :)
# on:
#   schedule:
#     - cron: "0 */72 * * *"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm install
        name: Install dependencies

      - run: npm run test
        name: Run test and lint

      - run: npm run build
        name: Build
        env:
          NODE_ENV: production
          ENVIRONMENT: ${{ contains(github.ref, 'master') && 'production' || 'staging'}}
          DELIVERY_ACCESS_TOKEN: ${{ secrets.DELIVERY_ACCESS_TOKEN }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
          GATSBY_DISQUS_NAME: ${{ secrets.GATSBY_DISQUS_NAME }}
          GATSBY_ENDPOINT: ${{ secrets.GATSBY_ENDPOINT }}
          GATSBY_FORM_ENDPOINT: ${{ secrets.GATSBY_FORM_ENDPOINT }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0
        with:
          publish-dir: "./public"
          production-branch: master
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
